# Dependencies
highlighter:      rouge

# Permalinks
#permalink:        pretty

# Setup
title:            Mark Whitby
tagline:          'Cloud // Automation // Code'
description:      'Cloud &middot; Automation &middot; Code'

url:              http://markw.me
baseurl:          /

author:
  name:           'Mark Whitby'
  url:            https://twitter.com/chipfat

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde

twitter_username: chipfat
permalink: /:title/

theme: jekyll-theme-cayman
