# Site settings
title: markw.me
description: > # this means to ignore newlines until "baseurl:"
  Techie bloke, knows a thing or two about computers, Windows platform specialist, app and web developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://markw.me" # the base hostname & protocol for your site
twitter_username: chipfat
permalink: /:year/:month/:day/:title/
# Build settings
markdown: kramdown
